FROM node:22.22.0-alpine3.22 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . . 
RUN npm run build -- --configuration production

FROM nginx:alpine
COPY --from=build /app/dist/authfront/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx","-g","daemon off;"]

