server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  # Redirection vers le Backend (Reverse Proxy)
      location /auth/ {
          proxy_pass http://authapp-back:8080/; # "authapp-back" est le nom du service dans docker-compose
          proxy_set_header Host $host;
      }
}
